import ReportChart from "../components/ReportChart";
import jsPDF from "jspdf";

function Reports() {
  const downloadPDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text("ReceiptHawk Expense Report", 20, 20);

    doc.setFontSize(14);

    doc.text("Total Expense : ₹15,000", 20, 45);
    doc.text("Total Budget : ₹20,000", 20, 60);
    doc.text("Remaining Budget : ₹5,000", 20, 75);
    doc.text("Average Expense : ₹5,000", 20, 90);

    doc.text("Highest Spending Category : Food", 20, 110);
    doc.text("Monthly Expense : ₹18,000", 20, 125);

    // Draw a professional horizontal line
    doc.line(20, 140, 180, 140);

    doc.setFontSize(12);
    doc.text("Generated by ReceiptHawk", 20, 155);

    doc.save("Expense_Report.pdf");
  };

  return (
    <div
      style={{
        padding: "40px",
        backgroundColor: "#fafafa",
        minHeight: "100vh"
      }}
    >
      {/* Heading */}
      <div style={{ marginBottom: "40px" }}>
        <h1
          style={{
            marginBottom: "14px",
            fontSize: "58px",
            fontWeight: "700",
            lineHeight: "1.1"
          }}
        >
          Financial Reports
        </h1>

        <p
          style={{
            color: "#64748b",
            fontSize: "18px",
            fontWeight: "500",
            lineHeight: "1.5"
          }}
        >
          Analyze monthly spending trends and insights
        </p>

        {/* Download Button */}
        <div
          style={{
            display: "flex",
            justifyContent: "flex-end",
            marginTop: "20px"
          }}
        >
          <button
            onClick={downloadPDF}
            style={{
              backgroundColor: "#2563eb",
              color: "white",
              border: "none",
              padding: "12px 24px",
              borderRadius: "10px",
              fontSize: "16px",
              cursor: "pointer",
              fontWeight: "bold",
              boxShadow: "0 5px 15px rgba(37,99,235,0.3)"
            }}
          >
            📄 Download Report
          </button>
        </div>
      </div>

      {/* Summary Cards */}
      <div
        style={{
          display: "flex",
          gap: "20px",
          marginBottom: "35px",
          flexWrap: "wrap"
        }}
      >
        <div
          style={{
            padding: "22px",
            borderRadius: "16px",
            boxShadow: "0 8px 20px rgba(0,0,0,0.08)",
            width: "220px",
            backgroundColor: "white"
          }}
        >
          <h3>Total Expense</h3>
          <h2>₹15,000</h2>
        </div>

        <div
          style={{
            padding: "22px",
            borderRadius: "16px",
            boxShadow: "0 8px 20px rgba(0,0,0,0.08)",
            width: "220px",
            backgroundColor: "white"
          }}
        >
          <h3>Highest Month</h3>
          <h2>February</h2>
        </div>

        <div
          style={{
            padding: "22px",
            borderRadius: "16px",
            boxShadow: "0 8px 20px rgba(0,0,0,0.08)",
            width: "220px",
            backgroundColor: "white"
          }}
        >
          <h3>Average Expense</h3>
          <h2>₹5,000</h2>
        </div>
      </div>

      {/* Chart */}
      <div
        style={{
          marginBottom: "35px",
          padding: "25px",
          backgroundColor: "white",
          borderRadius: "20px",
          boxShadow: "0 8px 24px rgba(0,0,0,0.08)",
          width: "fit-content"
        }}
      >
        <ReportChart />
      </div>

      {/* Expense Table */}
      <table
        style={{
          borderCollapse: "collapse",
          width: "70%",
          backgroundColor: "white",
          boxShadow: "0 8px 24px rgba(0,0,0,0.08)",
          borderRadius: "16px",
          overflow: "hidden"
        }}
      >
        <thead>
          <tr style={{ backgroundColor: "#f1f5f9" }}>
            <th
              style={{
                border: "1px solid #cbd5e1",
                padding: "14px"
              }}
            >
              Month
            </th>

            <th
              style={{
                border: "1px solid #cbd5e1",
                padding: "14px"
              }}
            >
              Expense
            </th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td
              style={{
                border: "1px solid #cbd5e1",
                padding: "14px"
              }}
            >
              January
            </td>

            <td
              style={{
                border: "1px solid #cbd5e1",
                padding: "14px"
              }}
            >
              ₹5,000
            </td>
          </tr>

          <tr>
            <td
              style={{
                border: "1px solid #cbd5e1",
                padding: "14px"
              }}
            >
              February
            </td>

            <td
              style={{
                border: "1px solid #cbd5e1",
                padding: "14px"
              }}
            >
              ₹7,000
            </td>
          </tr>

          <tr>
            <td
              style={{
                border: "1px solid #cbd5e1",
                padding: "14px"
              }}
            >
              March
            </td>

            <td
              style={{
                border: "1px solid #cbd5e1",
                padding: "14px"
              }}
            >
              ₹3,000
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default Reports;