spring.application.name=backend

# Server Port
server.port=8083

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/receipthawk
spring.datasource.username=root
spring.datasource.password=karishmanehasiri@123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# File Upload Configuration
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB